[tool.poetry]
name = "twitch-emote-analysis"
version = "0.1.0"
description = ""
authors = ["Bruno Queiroz <brunoldqueiroz@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
